apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "the-captains-hook.acme.com"
webhooks:
  - name: "the-captains-hook.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: the-captains-hook
        path: /validate-pods
        port: 443
      caBundle: |

    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
