apiVersion: v1
kind: Pod
metadata:
  labels:
    acme.com/lifespan-requested: "7"
  name: hello-good
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: hello-world
      name: hello-good
  restartPolicy: Always