apiVersion: v1
kind: Pod
metadata:
  labels:
    acme.com/lifespan-requested: "7"
  name: nginx-fail
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: nginx
      name: nginx-fail
  restartPolicy: Always