apiVersion: v1
kind: Pod
metadata:
  labels:
    acme.com/lifespan-requested: "7"
  name: alpine-good
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "180"
      image: alpine
      name: alpine-good
  restartPolicy: Always